### ISSUE TITLE
Tuda error. 

### ISSUE THREAD

**Issue by Tortoise17** [german-asr/megs#1]
Dear Friend. 

There is one message. 

Voxforge already exists
Download TUDA
Traceback (most recent call last):
  File "scripts/download.py", line 81, in <module>
    run()
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/download.py", line 46, in run
    tuda_dl = io.TudaDownloader()
AttributeError: module 'audiomate.corpus.io' has no attribute 'TudaDownloader'
[user@nb040 megs]$ python3 scripts/download.py data/download/.
Voxforge already exists
TUDA already exists
Download SWC
Traceback (most recent call last):
  File "scripts/download.py", line 81, in <module>
    run()
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/download.py", line 60, in run
    swc_dl = io.SWCDownloader()
AttributeError: module 'audiomate.corpus.io' has no attribute 'SWCDownloader'
[user@nb040 megs]$ python3 scripts/download.py data/download/.
Voxforge already exists
TUDA already exists
SWC already exists
Download Mailabs
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/user/anaconda3/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/user/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/user/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/user/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/user/anaconda3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/user/anaconda3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa0eada1a90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/user/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.m-ailabs.bayern', port=80): Max retries exceeded with url: /?ddownload=410 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa0eada1a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/download.py", line 81, in <module>
    run()
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/download.py", line 75, in run
    mailabs_dl.download(mailabs_path)
  File "/home/user/.local/lib/python3.7/site-packages/audiomate/corpus/io/base.py", line 25, in download
    return self._download(target_path)
  File "/home/user/.local/lib/python3.7/site-packages/audiomate/corpus/io/mailabs.py", line 49, in _download
    download.download_file(download_url, tmp_file)
  File "/home/user/.local/lib/python3.7/site-packages/audiomate/utils/download.py", line 15, in download_file
    r = requests.get(url, stream=True)
  File "/home/user/anaconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.m-ailabs.bayern', port=80): Max retries exceeded with url: /?ddownload=410 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa0eada1a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

for TUDA and SWC there is audiomate error. and for M-AiLab is different error.

**Comment by ynop** [comment]
Please make sure you install most recent version of audiomate.
Check requirements.txt.
