### ISSUE TITLE
Utterance key extraction error

### ISSUE THREAD

**Issue by Tortoise17** [german-asr/megs#6]
!!

**Comment by Tortoise17** [comment]
I have tried different ways. 

Still I am facing issues. If you can point out. please. Its because of maybe my mistake or audiomate? 

```
##############################################################
# Merge and subset
##############################################################
Load corpora
 - common_voice ...
 - mailabs ...
 - swc ...
 - tuda ...
 - voxforge ...
Create Train/Dev/Test - if not already exist
Traceback (most recent call last):
  File "scripts/merge_and_subset.py", line 181, in <module>
    run()
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/merge_and_subset.py", line 41, in run
    prepare_corpus(corpus, name)
  File "scripts/merge_and_subset.py", line 112, in prepare_corpus
    train_utts = set(corpus.subviews['train'].utterances.keys())
KeyError: 'train'
##############################################################
# Get infos about merged corpus
##############################################################
Info file already there
##############################################################
# Generate equivalence state
##############################################################
Hash meta files
Hash audio files
Traceback (most recent call last):
  File "scripts/equivalence.py", line 125, in <module>
    cli()
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/equivalence.py", line 24, in generate
    state = generate_state(full_path)
  File "scripts/equivalence.py", line 66, in generate_state
    corpus = audiomate.Corpus.load(path)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/audiomate/corpus/corpus.py", line 123, in load
    return reader.load(path)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/audiomate/corpus/io/base.py", line 95, in load
    self.type(), ' '.join(missing_files), path))
OSError: Invalid data set of type default: files files.txt utterances.txt not found at data/full
##############################################################
# Normalize transcripts
##############################################################
Load source corpus
Traceback (most recent call last):
  File "scripts/normalize_text.py", line 55, in <module>
    run()
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "scripts/normalize_text.py", line 15, in run
    ds = audiomate.Corpus.load(full_folder)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/audiomate/corpus/corpus.py", line 123, in load
    return reader.load(path)
  File "/home/user/anaconda3/envs/prep/lib/python3.6/site-packages/audiomate/corpus/io/base.py", line 95, in load
    self.type(), ' '.join(missing_files), path))
OSError: Invalid data set of type default: files files.txt utterances.txt not found at data/full
##############################################################
# Waverize
##############################################################
Already waverized
```
